# setting open-pull-requests-limit to 0 disables dependabot (for now)
---
version: 2
updates:

  - directory: .
    package-ecosystem: pip
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
