---
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--py3-plus"
          - "--separate-from-import"
          - "--separate-relative"

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-encoding-pragma

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: 2.1.5
    hooks:
      - id: markdownlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - "--strict"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-setuptools"
