---
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
      - id: reorder-python-imports
        language_version: python3.6
        args:
          - "--py3-plus"
          - "--separate-from-import"
          - "--separate-relative"

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: flake8
        language_version: python3.6
      - id: requirements-txt-fixer
        files: requirements/*
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-encoding-pragma

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.15.0
    hooks:
      - id: yamllint
        args:
          - "--strict"
