---
language: python
python: 3.6

install:
  - pip install codecov -rrequirements/dev.txt

stages:
  - name: test
    if: (type = 'pull_request' or type = 'api')

  - name: publish
    if: >-
      (type = "push" OR type = "api") AND
      (tag =~
       /^v((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/)

jobs:
  include:
    - stage: test
      script:
        - make coverage
        - codecov

    - stage: publish
      script:
        - make publish
