#
# Copyright (C) 2019 - 2025 James E. King III (@jeking3) <jking@apache.org>
#
---
name: CI

on:
  push:
    branches:
      - main
      - fix/ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    name: "test on ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -rrequirements/dev.txt
      - run: make coverage
      - uses: codecov/codecov-action@v5
        if: "${{ matrix.python-version == '3.12' }}"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
